Ansible 1
Otus-DevOps-2020-11/matveevelli_infra pull request #13
Opened 2021-03-09 01:06 UTC by matveevelli

# Выполнено ДЗ №8

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
 - Установлен ansible
 - Запущена инфраструктура `stage` из `terraform`
 - Проверена инфраструктура с помощью `ping`
 - Создан статический и динамический инвентори
 - 
## Как запустить проект:
 - `ansible all -m ping`

## Как проверить работоспособность:
 - `ansible all -m ping`

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2021-03-11 07:31 UTC, mrgreyves requested changes
Здравствуйте!) variables copy.tf вот этот файлик стоит удалить из репы. ДЗ возвращаю на доработку.

2021-03-12 06:14 UTC, mrgreyves requested changes
![image](https://user-images.githubusercontent.com/34331259/110900145-534b6780-8313-11eb-9772-f09c5006dff3.png)
Вот тут лучше оставить что-то одно =)

2021-03-12 14:02 UTC, matveevelli commented
Добавлял обычный инвентори для git actions, пытался понять почему тесты не проходят)
убрал

2021-03-15 07:27 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Задания выполнено корректно, тесты не проходят потому что в образе для тестов нет утили yc. ДЗ принимаю!=)

2021-03-15 07:29 UTC, merged